function ReVAS

% get version number from readme.md
versionNo = RevasVersion;

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create GUI figure
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% get display dimensions and place the gui to the right edge of the display
r = groot;
revas.ppi = r.ScreenPixelsPerInch;
revas.screenSize = r.ScreenSize;
revas.fontSize = 12;

% create gui
guiSize = [min(revas.screenSize(3)*0.5,640) min(revas.screenSize(4)*0.5,480)];
revasPos = [(revas.screenSize(3:4)-guiSize)/2 guiSize];
revas.gui = figure('units','pixels',...
    'position',revasPos,...
    'menubar','none',...
    'toolbar','none',...
    'name',['ReVAS ' versionNo],...
    'numbertitle','off',...
    'resize','on',...
    'visible','off',...
    'closerequestfcn',{@RevasClose});


%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create menus
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% pipeline menu
revas.pipelineMenu = uimenu(revas.gui,'Text','Pipeline');
uimenu(revas.pipelineMenu,'Text','New','Accelerator','N','MenuSelectedFcn',{@PipelineTool,revas});
uimenu(revas.pipelineMenu,'Text','Open','Accelerator','O','MenuSelectedFcn',{@OpenPipeline,revas});
uimenu(revas.pipelineMenu,'Text','Edit','Accelerator','E','MenuSelectedFcn',{@PipelineTool,revas},'Enable','of');
uimenu(revas.pipelineMenu,'Text','Save','Accelerator','S','MenuSelectedFcn',{@SavePipeline,revas},'Enable','of');
uimenu(revas.pipelineMenu,'Text','Save As','Accelerator','A','MenuSelectedFcn',{@SaveAsPipeline,revas},'Enable','of');

% help menu
revas.helpMenu = uimenu(revas.gui,'Text','Help');
uimenu(revas.helpMenu,'Text','About','Accelerator','I','MenuSelectedFcn',{@RevasAbout,revas});
uimenu(revas.helpMenu,'Text','Report An Issue','MenuSelectedFcn',{@RevasReportIssue,revas});
uimenu(revas.helpMenu,'Text','Documentation','Accelerator','D','MenuSelectedFcn',{@RevasDocumentation,revas});

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create uicontrols
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pipePanelPos = [0 0.4 1/3 0.6];
revas.pipelinePanel = uipanel('Parent',revas.gui,...
             'units','normalized',...
             'Title','Pipeline',...
             'FontSize',revas.fontSize,...
             'position',pipePanelPos,...
             'tag','pipePanel');

videoPanelPos = [sum(pipePanelPos([1 3])) pipePanelPos(2:4)];
revas.videoPanel = uipanel('Parent',revas.gui,...
             'units','normalized',...
             'Title','Video Selection',...
             'FontSize',revas.fontSize,...
             'position',videoPanelPos,...
             'tag','videoPanel');    
         
globalPanelPos = [sum(videoPanelPos([1 3])) pipePanelPos(2:4)];
revas.globalPanel = uipanel('Parent',revas.gui,...
             'units','normalized',...
             'Title','Global Flags',...
             'FontSize',revas.fontSize,...
             'position',globalPanelPos,...
             'tag','globalPanel');   

logBoxPos = [0 0.1 1 pipePanelPos(2)-0.13];
revas.logBox = uicontrol(revas.gui,...
             'style','listbox',...
             'units','normalized',...
             'position',logBoxPos,...
             'fontsize',revas.fontSize,...
             'string',{},...
             'value',0,...
             'tooltip','Log window.',...
             'callback',{@EditParamsCallback});  
         
runPos = [.45 0 0.1 logBoxPos(2)];
revas.runButton = uicontrol(revas.gui,...
             'style','togglebutton',...
             'units','normalized',...
             'position',runPos,...
             'fontsize',revas.fontSize,...
             'string','Run',...
             'value',0,...
             'callback',{@RunPipeline}); 

revas.statusBar = axes(revas.gui,...
             'units','normalized',...
             'position',[0 sum(logBoxPos([2,4])) 1 0.03],...
             'xtick',[],'ytick',[],'tag','statusBar');         
         
% Make visible 
set(revas.gui,'visible','on');

    %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % pipeline menu callbacks
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    function RevasReportIssue(varargin)
        web('https://github.com/lowvisionresearch/ReVAS/issues', '-browser');
    end
    
    function RevasDocumentation(varargin)
        web('https://github.com/lowvisionresearch/ReVAS/wiki', '-browser');
    end

    function RunPipeline(varargin)
    end


    %% close callback
    function RevasClose(varargin)
        delete(revas.gui);
    end


end