function success = Tester_IsNaturalNumber

if ~IsNaturalNumber(pi) && ...
        all(IsNaturalNumber(randi(10,10,1))) && ...
        ~IsNaturalNumber(nan) && ...
        ~any(IsNaturalNumber([nan nan -3])) && ...
        IsNaturalNumber(0)
    success = true;
else
    success = false;
end