function success = Tester_IsPositiveRealNumber

if IsPositiveRealNumber(pi) && ...
        all(IsPositiveRealNumber(1:2:7)) && ... 
        ~IsPositiveRealNumber(nan) && ...
        ~any(IsPositiveRealNumber([nan nan -3])) && ...
        ~IsPositiveRealNumber(0) && ...
        IsPositiveRealNumber(2)
    success = true;
else
    success = false;
end