function success = Tester_IsOddNaturalNumber

if ~IsOddNaturalNumber(pi) && ...
        all(IsOddNaturalNumber(1:2:7)) && ... 
        ~IsOddNaturalNumber(nan) && ...
        ~any(IsOddNaturalNumber([nan nan -3])) && ...
        ~IsOddNaturalNumber(0) && ...
        ~IsOddNaturalNumber(2)
    success = true;
else
    success = false;
end