function success = Tester_IsPositiveInteger

if ~IsPositiveInteger(pi) && ...
        all(IsPositiveInteger(randi(10,10,1))) && ...
        ~IsPositiveInteger(nan) && ...
        ~any(IsPositiveInteger([nan nan -3])) && ...
        ~IsPositiveInteger(0)
    success = true;
else
    success = false;
end