function RevasAbout(varargin)
% RevasAbout(varargin)
% 
%   Modal window showing some basic info on ReVAS.
% 
% Mehmet N. Agaoglu 1/19/2020
%



revas = varargin{3};
RevasMessage(sprintf('RevasAbout launched.'),revas.gui.UserData.logBox);

guiSize = round([min(revas.screenSize(3)*0.75, 360) min(revas.screenSize(4)*0.75, 480)]);
versionNo = RevasVersion;

header = {...
    sprintf(['Retinal Video Analysis Suite\nv. %s\n'...
    'Copyright (c) 2020\nSight Enhancement Laboratory at Berkeley\n'...
    'School of Optometry\n'...
    'University of California, Berkeley, USA.\n--------------------------------------\n\n'],versionNo)};
authors = {...
    sprintf(['Authors\n-------------\n'...
      '\tMehmet N. Agaoglu, PhD (now at Apple Inc.)\nmnagaoglu@gmail.com\n\n'...
      '\tMatthew T. Sit (now at Google LLC.)\nmsit@berkeley.edu\n\n'... 
      '\tEmma Alexander, PhD \nealexander@berkeley.edu\n\n'...
      '\tDerek Wan\n\n'...
      '\tSusana T. L. Chung, OD, PhD\ns.chung@berkeley.edu\n\n'...
      '\tAustin J. Roorda, PhD\naroorda@berkeley.edu\n'])};

% create the GUI
fig = figure('units','pixels',...
    'position',[revas.gui.OuterPosition(1:2)+(revas.gui.OuterPosition(3:4)-guiSize)/2 guiSize],...
    'menubar','none',...
    'toolbar','none',...
    'name','About ReVAS',...
    'numbertitle','off',...
    'resize','off',...
    'visible','off',...
    'windowstyle','modal');

% create uicontrol for texts
uicontrol(fig,'Style','Text','units','normalized',...
    'outerposition',[0 .65 1 .3],...
    'fontsize',revas.fontSize,...
    'fontweight','bold',...
    'string',header); 
uicontrol(fig,'Style','Text','units','normalized',...
    'outerposition',[0 0 1 .65],...
    'fontsize',revas.fontSize,...
    'string',authors); 

% Make visible 
set(fig,'visible','on');

% prevent all other processes from starting until closed.
uiwait(fig);  




