function ShowLogCallback(src,~,varargin)

revas = varargin{1};

% do this only when user double-clicks on an item
if strcmp(get(revas.gui,'SelectionType'),'open')

    % create a modal figure
    fig = figure('units','normalized',...
        'position',[.2 .2 .4 .4],...
        'menubar','none',...
        'toolbar','none',...
        'name','ReVAS Log - since last launch...',...
        'numbertitle','off',...
        'resize','on',...
        'visible','off',...
        'windowstyle','modal');

    % create only on UI element which is a listbox
    logBox = uicontrol(fig,...
         'style','listbox',...
         'units','normalized',...
         'position',[0 0 1 1],...
         'fontsize',revas.fontSize,...
         'string',src.String,...
         'value',1,...
         'min',1,...
         'max',3,...
         'tooltip','Log window.');  %#ok<NASGU>

    % Make visible 
    set(fig,'visible','on'); 


end